import config = libconfig%lib{config}
import libs = \
  libavutil%lib{avutil} \
  $config

## Some targets references hidden/non-exported symbols and need to link statically.
#  NOTE: To resolve correctly the static prerequisite must come first.
import static = libavutil%liba{avutil}
exe{test-random_seed}: $static: include = ($c.target.system == 'win32-msvc')

requirements = [string_set] \
  '{"pixelutils": "pixelutils"}'

# AFAICT test-file is disabled upstream, but it works for all but
# windows so lets be selective.
for t : tests/c{* -lzo -file}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libconfig.$r)
        if($c == [null] || !$c)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "$\tskip test: libavutil/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs testscript
  {
    cwd = [path] $path.posix_representation($src_base/tests/)
  }
  ./: exe{test-$n}: include = $e
}

# needs some (any) file as input
exe{test-utf8}: test.arguments = $path.posix_string($src_base/tests/file.c)

## Build options.
#
import [once] libconfig%buildfile{common-configs}
