import config = libconfig%lib{config}
import libs = \
  libavfilter%lib{avfilter} \
  $config

requirements = [string_set] \
  '{"integral": "nlmeans_filter"}'

## NOTE: filtfmts requires filter names as input.
#  TODO: extract all enabled filters (from libconfig)
#        and add as input: exe{test-filtfmts}: test.arguments = <filters>
for t : tests/c{*.c -filtfmts}
{
  n = [string] $name($t)
  e = [bool] true
  for str: [string_set] $requirements
  {
    pair = [json] $json.parse($str)
    k = [string] $member_name($pair)
    if ($k == $n)
    {
      s = [string] "$member_value($pair)"
      v = [strings] $regex.split($s, ' ', ' ')
      for r: [strings] ($v)
      {
        c = $($config: libconfig.$r)
        if($c == [null] || !$c)
        {
          e = false
        }
      }
      if(!$e)
      {
        text "$\tskip test: libavfilter/tests/$n.$extension($t) \(requires: $s\)"
      }
    }
  }

  exe{test-$n}: $t $libs testscript
  {
    cwd = [path] $path.posix_representation($src_base/tests/)
  }
  ./: exe{test-$n}: include = $e
}

## Build options.
#
import [once] libconfig%buildfile{common-configs}
