
intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

import config = libconfig%lib{config}
impl_libs += $config
import intf_libs += \
  libavutil%lib{avutil}

## Some targets references hidden/non-exported symbols and need to link statically.
#  NOTE: To resolve correctly the static prerequisite must come first.
import static = libavutil%liba{avutil}
libul{swscale}: $static: include = ($c.target.system == 'win32-msvc')

lib{swscale}: libul{swscale}: \
              libswscale/h{**} \
              $impl_libs $intf_libs

# conditional source & assembly
import [once] libconfig%buildfile{conditional-src}
import config_asm = libconfig%file{config.asm}
import config_defs = libconfig%file{enabled-defines}

[rule_hint=c] \
libul{swscale-meta}: $impl_libs $intf_libs

libul{swscale}: enabled_source{swscale}: $config_defs json{files} libswscale/h{**}: \
                                       update = match

libua{swscale}: enabled_asm{swscale-a}: $config_defs $config_asm json{files} libua{swscale-meta}: \
                                      update = match

libus{swscale}: enabled_asm{swscale-s}: $config_defs $config_asm json{files} libus{swscale-meta}: \
                                      update = match

libs{swscale}: winres{swscale}: include = ($c.target.system == 'win32-msvc')
winres{swscale}: libswscale/rc{swscaleres} libus{swscale-meta}

# these c files are included, not built.
libul{swscale}: adhoc_source{swscale}: include = adhoc
adhoc_source{swscale}: libswscale/c{**_template}

# Build options.
#
import [once] libconfig%buildfile{common-configs}

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

c.poptions += "-I$out_pfx" "-I$src_pfx" -DBUILDING_swscale

obja{*}: c.poptions += -DCONFIG_STATIC
objs{*}: c.poptions += -DCONFIG_SHARED

libs{swscale}: def{swscale}: include = ($c.target.system == 'win32-msvc')
def{swscale}: libul{swscale}

if ($c.target.system == 'mingw32')
  c.loptions += -Wl,--export-all-symbols

# System libraries
sys_libs =
switch $c.target.class, $c.target.system
{
  case 'windows', 'win32-msvc'
    sys_libs += bcrypt.lib
  case 'windows', 'mingw32'
    sys_libs += -lbcrypt
}
c.libs += $sys_libs

switch ($c.id)
{
  case 'msvc'
  {
    c.coptions += -wd4003 -wd4018 -wd4146 -wd4244 -wd4305 -wd4554 -wd4133 -wd4333
    c.poptions += -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS
  }
}

# Export options.
#
lib{swscale}:
{
  c.export.poptions = "-I$out_pfx" "-I$src_pfx"
  c.export.libs = $intf_libs $sys_libs
}

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{swscale}: bin.lib.version = "-$version.project_id"
else
  lib{swscale}: bin.lib.version = "-$version.major.$version.minor"

# Install recreating subdirectories.
#
h{*}:
{
  install         = include/
  install.subdirs = true
}
